services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    image: kafka-producer:1.0
    container_name: kafka-producer
    restart: unless-stopped

    environment:
      - TZ=Asia/Phnom_Penh

    volumes:
      - ./release/config:/app/config:ro
      - ./runtime/producer/logs:/data/input/logs:ro

